CREATE TABLE public.bank_accounts (
    id bigint NOT NULL,
    account_digit character varying(5) NOT NULL,
    account_number character varying(20) NOT NULL,
    agency character varying(10) NOT NULL,
    bank_name character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.bank_accounts OWNER TO postgres;

ALTER TABLE public.bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE bank_accounts
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE public.expense_categories (
    id bigint NOT NULL,
    color character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.expense_categories OWNER TO postgres;

ALTER TABLE public.expense_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE expense_categories
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    bank_id bigint NOT NULL,
    category_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notified boolean NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    transaction_type character varying(255) NOT NULL,
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['REVENUE'::character varying, 'EXPENSE'::character varying])::text[])))
);

ALTER TABLE public.transactions OWNER TO postgres;

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expense_categories
    ADD CONSTRAINT expense_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);
